<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1,'ISO' => 'AF' ,'name' => "Afghanistan",'country_code' => 93),
            array('id' => 2,'ISO' => 'AL' ,'name' => "Albania",'country_code' => 355),
            array('id' => 3,'ISO' => 'DZ' ,'name' => "Algeria",'country_code' => 213),
            array('id' => 4,'ISO' => 'AS' ,'name' => "American Samoa",'country_code' => 1684),
            array('id' => 5,'ISO' => 'AD' ,'name' => "Andorra",'country_code' => 376),
            array('id' => 6,'ISO' => 'AO' ,'name' => "Angola",'country_code' => 244),
            array('id' => 7,'ISO' => 'AI' ,'name' => "Anguilla",'country_code' => 1264),
            array('id' => 8,'ISO' => 'AQ' ,'name' => "Antarctica",'country_code' => 0),
            array('id' => 9,'ISO' => 'AG' ,'name' => "Antigua And Barbuda",'country_code' => 1268),
            array('id' => 10,'ISO' => 'AR','name' => "Argentina",'country_code' => 54),
            array('id' => 11,'ISO' => 'AM','name' => "Armenia",'country_code' => 374),
            array('id' => 12,'ISO' => 'AW','name' => "Aruba",'country_code' => 297),
            array('id' => 13,'ISO' => 'AU','name' => "Australia",'country_code' => 61),
            array('id' => 14,'ISO' => 'AT','name' => "Austria",'country_code' => 43),
            array('id' => 15,'ISO' => 'AZ','name' => "Azerbaijan",'country_code' => 994),
            array('id' => 16,'ISO' => 'BS','name' => "Bahamas The",'country_code' => 1242),
            array('id' => 17,'ISO' => 'BH','name' => "Bahrain",'country_code' => 973),
            array('id' => 18,'ISO' => 'BD','name' => "Bangladesh",'country_code' => 880),
            array('id' => 19,'ISO' => 'BB','name' => "Barbados",'country_code' => 1246),
            array('id' => 20,'ISO' => 'BY','name' => "Belarus",'country_code' => 375),
            array('id' => 21,'ISO' => 'BE','name' => "Belgium",'country_code' => 32),
            array('id' => 22,'ISO' => 'BZ','name' => "Belize",'country_code' => 501),
            array('id' => 23,'ISO' => 'BJ','name' => "Benin",'country_code' => 229),
            array('id' => 24,'ISO' => 'BM','name' => "Bermuda",'country_code' => 1441),
            array('id' => 25,'ISO' => 'BT','name' => "Bhutan",'country_code' => 975),
            array('id' => 26,'ISO' => 'BO','name' => "Bolivia",'country_code' => 591),
            array('id' => 27,'ISO' => 'BA','name' => "Bosnia and Herzegovina",'country_code' => 387),
            array('id' => 28,'ISO' => 'BW','name' => "Botswana",'country_code' => 267),
            array('id' => 29,'ISO' => 'BV','name' => "Bouvet Island",'country_code' => 0),
            array('id' => 30,'ISO' => 'BR','name' => "Brazil",'country_code' => 55),
            array('id' => 31,'ISO' => 'IO','name' => "British Indian Ocean Territory",'country_code' => 246),
            array('id' => 32,'ISO' => 'BN','name' => "Brunei",'country_code' => 673),
            array('id' => 33,'ISO' => 'BG','name' => "Bulgaria",'country_code' => 359),
            array('id' => 34,'ISO' => 'BF','name' => "Burkina Faso",'country_code' => 226),
            array('id' => 35,'ISO' => 'BI','name' => "Burundi",'country_code' => 257),
            array('id' => 36,'ISO' => 'KH','name' => "Cambodia",'country_code' => 855),
            array('id' => 37,'ISO' => 'CM','name' => "Cameroon",'country_code' => 237),
            array('id' => 38,'ISO' => 'CA','name' => "Canada",'country_code' => 1),
            array('id' => 39,'ISO' => 'CV','name' => "Cape Verde",'country_code' => 238),
            array('id' => 40,'ISO' => 'KY','name' => "Cayman Islands",'country_code' => 1345),
            array('id' => 41,'ISO' => 'CF','name' => "Central African Republic",'country_code' => 236),
            array('id' => 42,'ISO' => 'TD','name' => "Chad",'country_code' => 235),
            array('id' => 43,'ISO' => 'CL','name' => "Chile",'country_code' => 56),
            array('id' => 44,'ISO' => 'CN','name' => "China",'country_code' => 86),
            array('id' => 45,'ISO' => 'CX','name' => "Christmas Island",'country_code' => 61),
            array('id' => 46,'ISO' => 'CC','name' => "Cocos (Keeling) Islands",'country_code' => 672),
            array('id' => 47,'ISO' => 'CO','name' => "Colombia",'country_code' => 57),
            array('id' => 48,'ISO' => 'KM','name' => "Comoros",'country_code' => 269),
            array('id' => 49,'ISO' => 'CG','name' => "Congo",'country_code' => 242),
            array('id' => 50,'ISO' => 'CD','name' => "Congo The Democratic Republic Of The",'country_code' => 242),
            array('id' => 51,'ISO' => 'CK','name' => "Cook Islands",'country_code' => 682),
            array('id' => 52,'ISO' => 'CR','name' => "Costa Rica",'country_code' => 506),
            array('id' => 53,'ISO' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'country_code' => 225),
            array('id' => 54,'ISO' => 'HR','name' => "Croatia (Hrvatska)",'country_code' => 385),
            array('id' => 55,'ISO' => 'CU','name' => "Cuba",'country_code' => 53),
            array('id' => 56,'ISO' => 'CY','name' => "Cyprus",'country_code' => 357),
            array('id' => 57,'ISO' => 'CZ','name' => "Czech Republic",'country_code' => 420),
            array('id' => 58,'ISO' => 'DK','name' => "Denmark",'country_code' => 45),
            array('id' => 59,'ISO' => 'DJ','name' => "Djibouti",'country_code' => 253),
            array('id' => 60,'ISO' => 'DM','name' => "Dominica",'country_code' => 1767),
            array('id' => 61,'ISO' => 'DO','name' => "Dominican Republic",'country_code' => 1809),
            array('id' => 62,'ISO' => 'TP','name' => "East Timor",'country_code' => 670),
            array('id' => 63,'ISO' => 'EC','name' => "Ecuador",'country_code' => 593),
            array('id' => 64,'ISO' => 'EG','name' => "Egypt",'country_code' => 20),
            array('id' => 65,'ISO' => 'SV','name' => "El Salvador",'country_code' => 503),
            array('id' => 66,'ISO' => 'GQ','name' => "Equatorial Guinea",'country_code' => 240),
            array('id' => 67,'ISO' => 'ER','name' => "Eritrea",'country_code' => 291),
            array('id' => 68,'ISO' => 'EE','name' => "Estonia",'country_code' => 372),
            array('id' => 69,'ISO' => 'ET','name' => "Ethiopia",'country_code' => 251),
            array('id' => 70,'ISO' => 'XA','name' => "External Territories of Australia",'country_code' => 61),
            array('id' => 71,'ISO' => 'FK','name' => "Falkland Islands",'country_code' => 500),
            array('id' => 72,'ISO' => 'FO','name' => "Faroe Islands",'country_code' => 298),
            array('id' => 73,'ISO' => 'FJ','name' => "Fiji Islands",'country_code' => 679),
            array('id' => 74,'ISO' => 'FI','name' => "Finland",'country_code' => 358),
            array('id' => 75,'ISO' => 'FR','name' => "France",'country_code' => 33),
            array('id' => 76,'ISO' => 'GF','name' => "French Guiana",'country_code' => 594),
            array('id' => 77,'ISO' => 'PF','name' => "French Polynesia",'country_code' => 689),
            array('id' => 78,'ISO' => 'TF','name' => "French Southern Territories",'country_code' => 0),
            array('id' => 79,'ISO' => 'GA','name' => "Gabon",'country_code' => 241),
            array('id' => 80,'ISO' => 'GM','name' => "Gambia The",'country_code' => 220),
            array('id' => 81,'ISO' => 'GE','name' => "Georgia",'country_code' => 995),
            array('id' => 82,'ISO' => 'DE','name' => "Germany",'country_code' => 49),
            array('id' => 83,'ISO' => 'GH','name' => "Ghana",'country_code' => 233),
            array('id' => 84,'ISO' => 'GI','name' => "Gibraltar",'country_code' => 350),
            array('id' => 85,'ISO' => 'GR','name' => "Greece",'country_code' => 30),
            array('id' => 86,'ISO' => 'GL','name' => "Greenland",'country_code' => 299),
            array('id' => 87,'ISO' => 'GD','name' => "Grenada",'country_code' => 1473),
            array('id' => 88,'ISO' => 'GP','name' => "Guadeloupe",'country_code' => 590),
            array('id' => 89,'ISO' => 'GU','name' => "Guam",'country_code' => 1671),
            array('id' => 90,'ISO' => 'GT','name' => "Guatemala",'country_code' => 502),
            array('id' => 91,'ISO' => 'XU','name' => "Guernsey and Alderney",'country_code' => 44),
            array('id' => 92,'ISO' => 'GN','name' => "Guinea",'country_code' => 224),
            array('id' => 93,'ISO' => 'GW','name' => "Guinea-Bissau",'country_code' => 245),
            array('id' => 94,'ISO' => 'GY','name' => "Guyana",'country_code' => 592),
            array('id' => 95,'ISO' => 'HT','name' => "Haiti",'country_code' => 509),
            array('id' => 96,'ISO' => 'HM','name' => "Heard and McDonald Islands",'country_code' => 0),
            array('id' => 97,'ISO' => 'HN','name' => "Honduras",'country_code' => 504),
            array('id' => 98,'ISO' => 'HK','name' => "Hong Kong S.A.R.",'country_code' => 852),
            array('id' => 99,'ISO' => 'HU','name' => "Hungary",'country_code' => 36),
            array('id' => 100,'ISO' => 'IS','name' => "Iceland",'country_code' => 354),
            array('id' => 101,'ISO' => 'IN','name' => "India",'country_code' => 91),
            array('id' => 102,'ISO' => 'ID','name' => "Indonesia",'country_code' => 62),
            array('id' => 103,'ISO' => 'IR','name' => "Iran",'country_code' => 98),
            array('id' => 104,'ISO' => 'IQ','name' => "Iraq",'country_code' => 964),
            array('id' => 105,'ISO' => 'IE','name' => "Ireland",'country_code' => 353),
            array('id' => 106,'ISO' => 'IL','name' => "Israel",'country_code' => 972),
            array('id' => 107,'ISO' => 'IT','name' => "Italy",'country_code' => 39),
            array('id' => 108,'ISO' => 'JM','name' => "Jamaica",'country_code' => 1876),
            array('id' => 109,'ISO' => 'JP','name' => "Japan",'country_code' => 81),
            array('id' => 110,'ISO' => 'XJ','name' => "Jersey",'country_code' => 44),
            array('id' => 111,'ISO' => 'JO','name' => "Jordan",'country_code' => 962),
            array('id' => 112,'ISO' => 'KZ','name' => "Kazakhstan",'country_code' => 7),
            array('id' => 113,'ISO' => 'KE','name' => "Kenya",'country_code' => 254),
            array('id' => 114,'ISO' => 'KI','name' => "Kiribati",'country_code' => 686),
            array('id' => 115,'ISO' => 'KP','name' => "Korea North",'country_code' => 850),
            array('id' => 116,'ISO' => 'KR','name' => "Korea South",'country_code' => 82),
            array('id' => 117,'ISO' => 'KW','name' => "Kuwait",'country_code' => 965),
            array('id' => 118,'ISO' => 'KG','name' => "Kyrgyzstan",'country_code' => 996),
            array('id' => 119,'ISO' => 'LA','name' => "Laos",'country_code' => 856),
            array('id' => 120,'ISO' => 'LV','name' => "Latvia",'country_code' => 371),
            array('id' => 121,'ISO' => 'LB','name' => "Lebanon",'country_code' => 961),
            array('id' => 122,'ISO' => 'LS','name' => "Lesotho",'country_code' => 266),
            array('id' => 123,'ISO' => 'LR','name' => "Liberia",'country_code' => 231),
            array('id' => 124,'ISO' => 'LY','name' => "Libya",'country_code' => 218),
            array('id' => 125,'ISO' => 'LI','name' => "Liechtenstein",'country_code' => 423),
            array('id' => 126,'ISO' => 'LT','name' => "Lithuania",'country_code' => 370),
            array('id' => 127,'ISO' => 'LU','name' => "Luxembourg",'country_code' => 352),
            array('id' => 128,'ISO' => 'MO','name' => "Macau S.A.R.",'country_code' => 853),
            array('id' => 129,'ISO' => 'MK','name' => "Macedonia",'country_code' => 389),
            array('id' => 130,'ISO' => 'MG','name' => "Madagascar",'country_code' => 261),
            array('id' => 131,'ISO' => 'MW','name' => "Malawi",'country_code' => 265),
            array('id' => 132,'ISO' => 'MY','name' => "Malaysia",'country_code' => 60),
            array('id' => 133,'ISO' => 'MV','name' => "Maldives",'country_code' => 960),
            array('id' => 134,'ISO' => 'ML','name' => "Mali",'country_code' => 223),
            array('id' => 135,'ISO' => 'MT','name' => "Malta",'country_code' => 356),
            array('id' => 136,'ISO' => 'XM','name' => "Man (Isle of)",'country_code' => 44),
            array('id' => 137,'ISO' => 'MH','name' => "Marshall Islands",'country_code' => 692),
            array('id' => 138,'ISO' => 'MQ','name' => "Martinique",'country_code' => 596),
            array('id' => 139,'ISO' => 'MR','name' => "Mauritania",'country_code' => 222),
            array('id' => 140,'ISO' => 'MU','name' => "Mauritius",'country_code' => 230),
            array('id' => 141,'ISO' => 'YT','name' => "Mayotte",'country_code' => 269),
            array('id' => 142,'ISO' => 'MX','name' => "Mexico",'country_code' => 52),
            array('id' => 143,'ISO' => 'FM','name' => "Micronesia",'country_code' => 691),
            array('id' => 144,'ISO' => 'MD','name' => "Moldova",'country_code' => 373),
            array('id' => 145,'ISO' => 'MC','name' => "Monaco",'country_code' => 377),
            array('id' => 146,'ISO' => 'MN','name' => "Mongolia",'country_code' => 976),
            array('id' => 147,'ISO' => 'MS','name' => "Montserrat",'country_code' => 1664),
            array('id' => 148,'ISO' => 'MA','name' => "Morocco",'country_code' => 212),
            array('id' => 149,'ISO' => 'MZ','name' => "Mozambique",'country_code' => 258),
            array('id' => 150,'ISO' => 'MM','name' => "Myanmar",'country_code' => 95),
            array('id' => 151,'ISO' => 'NA','name' => "Namibia",'country_code' => 264),
            array('id' => 152,'ISO' => 'NR','name' => "Nauru",'country_code' => 674),
            array('id' => 153,'ISO' => 'NP','name' => "Nepal",'country_code' => 977),
            array('id' => 154,'ISO' => 'AN','name' => "Netherlands Antilles",'country_code' => 599),
            array('id' => 155,'ISO' => 'NL','name' => "Netherlands The",'country_code' => 31),
            array('id' => 156,'ISO' => 'NC','name' => "New Caledonia",'country_code' => 687),
            array('id' => 157,'ISO' => 'NZ','name' => "New Zealand",'country_code' => 64),
            array('id' => 158,'ISO' => 'NI','name' => "Nicaragua",'country_code' => 505),
            array('id' => 159,'ISO' => 'NE','name' => "Niger",'country_code' => 227),
            array('id' => 160,'ISO' => 'NG','name' => "Nigeria",'country_code' => 234),
            array('id' => 161,'ISO' => 'NU','name' => "Niue",'country_code' => 683),
            array('id' => 162,'ISO' => 'NF','name' => "Norfolk Island",'country_code' => 672),
            array('id' => 163,'ISO' => 'MP','name' => "Northern Mariana Islands",'country_code' => 1670),
            array('id' => 164,'ISO' => 'NO','name' => "Norway",'country_code' => 47),
            array('id' => 165,'ISO' => 'OM','name' => "Oman",'country_code' => 968),
            array('id' => 166,'ISO' => 'PK','name' => "Pakistan",'country_code' => 92),
            array('id' => 167,'ISO' => 'PW','name' => "Palau",'country_code' => 680),
            array('id' => 168,'ISO' => 'PS','name' => "Palestinian Territory Occupied",'country_code' => 970),
            array('id' => 169,'ISO' => 'PA','name' => "Panama",'country_code' => 507),
            array('id' => 170,'ISO' => 'PG','name' => "Papua new Guinea",'country_code' => 675),
            array('id' => 171,'ISO' => 'PY','name' => "Paraguay",'country_code' => 595),
            array('id' => 172,'ISO' => 'PE','name' => "Peru",'country_code' => 51),
            array('id' => 173,'ISO' => 'PH','name' => "Philippines",'country_code' => 63),
            array('id' => 174,'ISO' => 'PN','name' => "Pitcairn Island",'country_code' => 0),
            array('id' => 175,'ISO' => 'PL','name' => "Poland",'country_code' => 48),
            array('id' => 176,'ISO' => 'PT','name' => "Portugal",'country_code' => 351),
            array('id' => 177,'ISO' => 'PR','name' => "Puerto Rico",'country_code' => 1787),
            array('id' => 178,'ISO' => 'QA','name' => "Qatar",'country_code' => 974),
            array('id' => 179,'ISO' => 'RE','name' => "Reunion",'country_code' => 262),
            array('id' => 180,'ISO' => 'RO','name' => "Romania",'country_code' => 40),
            array('id' => 181,'ISO' => 'RU','name' => "Russia",'country_code' => 70),
            array('id' => 182,'ISO' => 'RW','name' => "Rwanda",'country_code' => 250),
            array('id' => 183,'ISO' => 'SH','name' => "Saint Helena",'country_code' => 290),
            array('id' => 184,'ISO' => 'KN','name' => "Saint Kitts And Nevis",'country_code' => 1869),
            array('id' => 185,'ISO' => 'LC','name' => "Saint Lucia",'country_code' => 1758),
            array('id' => 186,'ISO' => 'PM','name' => "Saint Pierre and Miquelon",'country_code' => 508),
            array('id' => 187,'ISO' => 'VC','name' => "Saint Vincent And The Grenadines",'country_code' => 1784),
            array('id' => 188,'ISO' => 'WS','name' => "Samoa",'country_code' => 684),
            array('id' => 189,'ISO' => 'SM','name' => "San Marino",'country_code' => 378),
            array('id' => 190,'ISO' => 'ST','name' => "Sao Tome and Principe",'country_code' => 239),
            array('id' => 191,'ISO' => 'SA','name' => "Saudi Arabia",'country_code' => 966),
            array('id' => 192,'ISO' => 'SN','name' => "Senegal",'country_code' => 221),
            array('id' => 193,'ISO' => 'RS','name' => "Serbia",'country_code' => 381),
            array('id' => 194,'ISO' => 'SC','name' => "Seychelles",'country_code' => 248),
            array('id' => 195,'ISO' => 'SL','name' => "Sierra Leone",'country_code' => 232),
            array('id' => 196,'ISO' => 'SG','name' => "Singapore",'country_code' => 65),
            array('id' => 197,'ISO' => 'SK','name' => "Slovakia",'country_code' => 421),
            array('id' => 198,'ISO' => 'SI','name' => "Slovenia",'country_code' => 386),
            array('id' => 199,'ISO' => 'XG','name' => "Smaller Territories of the UK",'country_code' => 44),
            array('id' => 200,'ISO' => 'SB','name' => "Solomon Islands",'country_code' => 677),
            array('id' => 201,'ISO' => 'SO','name' => "Somalia",'country_code' => 252),
            array('id' => 202,'ISO' => 'ZA','name' => "South Africa",'country_code' => 27),
            array('id' => 203,'ISO' => 'GS','name' => "South Georgia",'country_code' => 0),
            array('id' => 204,'ISO' => 'SS','name' => "South Sudan",'country_code' => 211),
            array('id' => 205,'ISO' => 'ES','name' => "Spain",'country_code' => 34),
            array('id' => 206,'ISO' => 'LK','name' => "Sri Lanka",'country_code' => 94),
            array('id' => 207,'ISO' => 'SD','name' => "Sudan",'country_code' => 249),
            array('id' => 208,'ISO' => 'SR','name' => "Suriname",'country_code' => 597),
            array('id' => 209,'ISO' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'country_code' => 47),
            array('id' => 210,'ISO' => 'SZ','name' => "Swaziland",'country_code' => 268),
            array('id' => 211,'ISO' => 'SE','name' => "Sweden",'country_code' => 46),
            array('id' => 212,'ISO' => 'CH','name' => "Switzerland",'country_code' => 41),
            array('id' => 213,'ISO' => 'SY','name' => "Syria",'country_code' => 963),
            array('id' => 214,'ISO' => 'TW','name' => "Taiwan",'country_code' => 886),
            array('id' => 215,'ISO' => 'TJ','name' => "Tajikistan",'country_code' => 992),
            array('id' => 216,'ISO' => 'TZ','name' => "Tanzania",'country_code' => 255),
            array('id' => 217,'ISO' => 'TH','name' => "Thailand",'country_code' => 66),
            array('id' => 218,'ISO' => 'TG','name' => "Togo",'country_code' => 228),
            array('id' => 219,'ISO' => 'TK','name' => "Tokelau",'country_code' => 690),
            array('id' => 220,'ISO' => 'TO','name' => "Tonga",'country_code' => 676),
            array('id' => 221,'ISO' => 'TT','name' => "Trinidad And Tobago",'country_code' => 1868),
            array('id' => 222,'ISO' => 'TN','name' => "Tunisia",'country_code' => 216),
            array('id' => 223,'ISO' => 'TR','name' => "Turkey",'country_code' => 90),
            array('id' => 224,'ISO' => 'TM','name' => "Turkmenistan",'country_code' => 7370),
            array('id' => 225,'ISO' => 'TC','name' => "Turks And Caicos Islands",'country_code' => 1649),
            array('id' => 226,'ISO' => 'TV','name' => "Tuvalu",'country_code' => 688),
            array('id' => 227,'ISO' => 'UG','name' => "Uganda",'country_code' => 256),
            array('id' => 228,'ISO' => 'UA','name' => "Ukraine",'country_code' => 380),
            array('id' => 229,'ISO' => 'AE','name' => "United Arab Emirates",'country_code' => 971),
            array('id' => 230,'ISO' => 'GB','name' => "United Kingdom",'country_code' => 44),
            array('id' => 231,'ISO' => 'US','name' => "United States",'country_code' => 1),
            array('id' => 232,'ISO' => 'UM','name' => "United States Minor Outlying Islands",'country_code' => 1),
            array('id' => 233,'ISO' => 'UY','name' => "Uruguay",'country_code' => 598),
            array('id' => 234,'ISO' => 'UZ','name' => "Uzbekistan",'country_code' => 998),
            array('id' => 235,'ISO' => 'VU','name' => "Vanuatu",'country_code' => 678),
            array('id' => 236,'ISO' => 'VA','name' => "Vatican City State (Holy See)",'country_code' => 39),
            array('id' => 237,'ISO' => 'VE','name' => "Venezuela",'country_code' => 58),
            array('id' => 238,'ISO' => 'VN','name' => "Vietnam",'country_code' => 84),
            array('id' => 239,'ISO' => 'VG','name' => "Virgin Islands (British)",'country_code' => 1284),
            array('id' => 240,'ISO' => 'VI','name' => "Virgin Islands (US)",'country_code' => 1340),
            array('id' => 241,'ISO' => 'WF','name' => "Wallis And Futuna Islands",'country_code' => 681),
            array('id' => 242,'ISO' => 'EH','name' => "Western Sahara",'country_code' => 212),
            array('id' => 243,'ISO' => 'YE','name' => "Yemen",'country_code' => 967),
            array('id' => 244,'ISO' => 'YU','name' => "Yugoslavia",'country_code' => 38),
            array('id' => 245,'ISO' => 'ZM','name' => "Zambia",'country_code' => 260),
            array('id' => 246,'ISO' => 'ZW','name' => "Zimbabwe",'country_code' => 263),
        );
		DB::table('countries')->insert($countries);
    }
}
